# Pauli Matrices

파울리 행렬의 아이겐밸류와 아이겐벡터를 구하시오.

$$ s_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad
s_y = \begin{pmatrix} 0 & -j \\ j & 0 \end{pmatrix}, \quad
s_z  = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}. $$

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

sx = np.array([[0,1],
              [1,0]])
sy = np.array([[0,-1j],
               [1j,0]])
sz = np.array([[1,0],
               [0,-1]])
np.linalg.eig(sx), np.linalg.eig(sy), np.linalg.eig(sz)

((array([ 1., -1.]),
  array([[ 0.70710678, -0.70710678],
         [ 0.70710678,  0.70710678]])),
 (array([ 1.+0.j, -1.+0.j]),
  array([[-0.        -0.70710678j,  0.70710678+0.j        ],
         [ 0.70710678+0.j        ,  0.        -0.70710678j]])),
 (array([ 1., -1.]),
  array([[1., 0.],
         [0., 1.]])))

##  Modes
(고전역학 by Thornton & Marion 챕터 12.2 및 예제 12.3 참조) 용수철 상수가 $k$인 용수철에 연결된 두 개의 물체의 노말 모드를 구해보자. 두 개의 물체의 운동방정식은 다음으로 주어진다.$$ -m w^2 x_1 = -2kx_1 +k x_2, \\
-m w^2 x_2 = k x_1 - 2 k x_2.$$eigenfrequencies $w$는 다음의 행렬식을 통해 구할 수 있다.$$ \frac{k}{m w^2} \begin{pmatrix} 2 & -1 \\ -1 & 2 \end{pmatrix} 
\begin{pmatrix} x_1 \\ x_2 \end{pmatrix}=
\lambda \begin{pmatrix} x_1 \\ x_2 \end{pmatrix} $$

In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

m = np.array([[2,-1],
              [-1,2]])
np.linalg.eig(m)

(array([3., 1.]),
 array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]))

따라서 eigenfrequencies는$$ w_1 = \sqrt{\frac{k}{m}}, \quad w_2 = \sqrt{\frac{3k}{m}}. $$

위에서 구한 아이겐벡터와 아이겐밸류의 의미를 설명하여라.

eigenvalue는 3과 1로, 위 행렬 식에서 $\lambda$의 값에 해당한다. 

2x2행렬이기 때문에 $\lambda$는 2개의 eigenvalue 값을 갖는다.

eigenvalue는 eigenfrequencies $\omega$를 결정하며 $ \omega=\sqrt{\frac{\lambda k}{m}}$ 이다.

위 행렬에서 $\lambda$에 eigenvalue를 넣고 행렬을 풀면 $x_1$과 $x_2$의 비를 구할 수 있다. 

$\lambda$=3일 때 $x_1$:$x_2$=$\sqrt{\frac{1}{2}}$: -$\sqrt{\frac{1}{2}}$로 두 물체는 같은 크기와 반대방향으로 운동한다.

$\lambda$=1일 때 $x_1$:$x_2$=$\sqrt{\frac{1}{2}}$:$\sqrt{\frac{1}{2}}$로 두 물체는 같은 크기와 방향으로 운동한다.

이 비는 eigenvector를 나타내며 eigenvector는 두 물체의 운동의 크기와 방향을 나타낸다.